// <auto-generated />
using System;
using KssGroupPlanning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KssGroupPlanning.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250918164702_migration_v5")]
    partial class migration_v5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountEmployee")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("Brigades");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupMaterials");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("FactoryEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactoryEntityId");

                    b.HasIndex("OrderEntityId");

                    b.HasIndex("ParentProductEntityId");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeEntityId");

                    b.ToTable("ProductSubTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialId");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleId");

                    b.ToTable("ProductSubTypeGroupMaterialRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStageSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("ProductSubTypeStageSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StandartEmployee")
                        .HasColumnType("integer");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingPeriodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("ProductSubTypeWorkingPeriodSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.SrcOrderEntity", b =>
                {
                    b.Property<string>("OrderName")
                        .HasColumnType("text");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Dogovor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LogisticDate")
                        .HasColumnType("date");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SchemeDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderName");

                    b.ToTable("SrcOrders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StageTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntityId");

                    b.ToTable("WorkingPeriods");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProductSubTypeWokingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentProductSubTypeWokingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasIndex("ParentProductSubTypeWorkingPeriodSampleEntityId");

                    b.ToTable("WorkingPeriodRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageBrigadeRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrigadeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrigadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingPeriodStageEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrigadeEntityId");

                    b.HasIndex("WorkingPeriodStageEntityId");

                    b.ToTable("WorkingPeriodStageBrigadeRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Recycling")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleId");

                    b.HasIndex("WorkingPeriodId");

                    b.ToTable("WorkingPeriodStages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateDelivery")
                        .HasColumnType("date");

                    b.Property<Guid>("GroupMaterialEntitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialEntitiesId");

                    b.HasIndex("WorkingPeriodStageEntityId");

                    b.ToTable("WorkingPeriodStageMaterials");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageTypeRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("WorkingPeriodStageTypeRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "FactoryEntity")
                        .WithMany("Products")
                        .HasForeignKey("FactoryEntityId");

                    b.HasOne("KssGroupPlanning.Entities.OrderEntity", "OrderEntity")
                        .WithMany("Products")
                        .HasForeignKey("OrderEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ParentProductEntity")
                        .WithMany("ChildProductEntities")
                        .HasForeignKey("ParentProductEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("FactoryEntity");

                    b.Navigation("OrderEntity");

                    b.Navigation("ParentProductEntity");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductTypeEntity", "ProductTypeEntity")
                        .WithMany("ProductSubTypeEntities")
                        .HasForeignKey("ProductTypeEntityId");

                    b.Navigation("ProductTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterial")
                        .WithMany()
                        .HasForeignKey("GroupMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMaterial");

                    b.Navigation("ProductSubTypeWorkingPeriodSample");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStageSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ProductEntity")
                        .WithMany()
                        .HasForeignKey("ProductEntityId");

                    b.Navigation("ProductEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ChildProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ChildProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ParentProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ParentProductSubTypeWorkingPeriodSampleEntityId");

                    b.Navigation("ChildProductSubTypeWorkingPeriodSampleEntity");

                    b.Navigation("ParentProductSubTypeWorkingPeriodSampleEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageBrigadeRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.BrigadeEntity", "BrigadeEntity")
                        .WithMany()
                        .HasForeignKey("BrigadeEntityId");

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", "WorkingPeriodStageEntity")
                        .WithMany()
                        .HasForeignKey("WorkingPeriodStageEntityId");

                    b.Navigation("BrigadeEntity");

                    b.Navigation("WorkingPeriodStageEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodEntity", "WorkingPeriod")
                        .WithMany()
                        .HasForeignKey("WorkingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWorkingPeriodSample");

                    b.Navigation("WorkingPeriod");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterialEntities")
                        .WithMany("WorkingPeriodStageMaterialEntities")
                        .HasForeignKey("GroupMaterialEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", "WorkingPeriodStageEntity")
                        .WithMany("workingPeriodStageMaterialEntities")
                        .HasForeignKey("WorkingPeriodStageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMaterialEntities");

                    b.Navigation("WorkingPeriodStageEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageTypeRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWorkingPeriodSampleEntity");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Navigation("WorkingPeriodStageMaterialEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Navigation("ChildProductEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductSubTypeEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Navigation("workingPeriodStageMaterialEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
