// <auto-generated />
using System;
using KssGroupPlanning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KssGroupPlanning.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250928160726_new_entities_v6")]
    partial class new_entities_v6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrigadeEntityWorkingPeriodStageEntity", b =>
                {
                    b.Property<Guid>("BrigadesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStagesId")
                        .HasColumnType("uuid");

                    b.HasKey("BrigadesId", "WorkingPeriodStagesId");

                    b.HasIndex("WorkingPeriodStagesId");

                    b.ToTable("BrigadeEntityWorkingPeriodStageEntity");
                });

            modelBuilder.Entity("GroupMaterialEntityProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.Property<Guid>("GroupMaterialsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSamplesId")
                        .HasColumnType("uuid");

                    b.HasKey("GroupMaterialsId", "ProductSubTypeWorkingPeriodSamplesId");

                    b.HasIndex("ProductSubTypeWorkingPeriodSamplesId");

                    b.ToTable("GroupMaterialEntityProductSubTypeWorkingPeriodSampleEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountEmployee")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("Brigade");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factory");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupMaterial");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ParentProductId");

                    b.HasIndex("ProductSubTypeId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("ProductSubType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialId");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleId");

                    b.ToTable("ProductSubTypeGroupMaterialRelation");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStageSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeId");

                    b.ToTable("ProductSubTypeStageSample");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StandartEmployee")
                        .HasColumnType("integer");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingPeriodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeId");

                    b.ToTable("ProductSubTypeWorkingPeriodSample");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.SrcOrderEntity", b =>
                {
                    b.Property<string>("OrderName")
                        .HasColumnType("text");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Dogovor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LogisticDate")
                        .HasColumnType("date");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SchemeDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderName");

                    b.ToTable("SrcOrder");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WorkingPeriod");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasIndex("ParentProductSubTypeWorkingPeriodSampleEntityId");

                    b.ToTable("WorkingPeriodRelation");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageBrigadeRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrigadeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrigadeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WorkingPeriodStageEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrigadeEntityId");

                    b.HasIndex("WorkingPeriodStageEntityId");

                    b.ToTable("WorkingPeriodStageBrigadeRelation");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Recycling")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleId");

                    b.HasIndex("WorkingPeriodId");

                    b.ToTable("WorkingPeriodStage");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateDelivery")
                        .HasColumnType("date");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialId");

                    b.HasIndex("WorkingPeriodStageId");

                    b.ToTable("WorkingPeriodStageMaterial");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageTypeRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeWorkingPeriodSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("WorkingPeriodStageTypeRelation");
                });

            modelBuilder.Entity("ProductSubTypeWorkingPeriodSampleEntityProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.Property<Guid>("ChildProductSubTypeWorkingPeriodSamplesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentProductSubTypeWorkingPeriodSamplesId")
                        .HasColumnType("uuid");

                    b.HasKey("ChildProductSubTypeWorkingPeriodSamplesId", "ParentProductSubTypeWorkingPeriodSamplesId");

                    b.HasIndex("ParentProductSubTypeWorkingPeriodSamplesId");

                    b.ToTable("ProductSubTypeWorkingPeriodSampleEntityProductSubTypeWorkingPe~");
                });

            modelBuilder.Entity("ProductSubTypeWorkingPeriodSampleEntityStageTypeEntity", b =>
                {
                    b.Property<Guid>("ProductSubTypeWorkingPeriodSamplesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypesId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductSubTypeWorkingPeriodSamplesId", "StageTypesId");

                    b.HasIndex("StageTypesId");

                    b.ToTable("ProductSubTypeWorkingPeriodSampleEntityStageTypeEntity");
                });

            modelBuilder.Entity("BrigadeEntityWorkingPeriodStageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.BrigadeEntity", null)
                        .WithMany()
                        .HasForeignKey("BrigadesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", null)
                        .WithMany()
                        .HasForeignKey("WorkingPeriodStagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMaterialEntityProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", null)
                        .WithMany()
                        .HasForeignKey("GroupMaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSamplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GroupMaterialEntityProductSubTypeWorkingPeriodSampleEntity~1");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "Factory")
                        .WithMany("Brigades")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany("Brigades")
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "Factory")
                        .WithMany("Products")
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.OrderEntity", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ParentProduct")
                        .WithMany("ChildProducts")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubType")
                        .WithMany("Products")
                        .HasForeignKey("ProductSubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("Order");

                    b.Navigation("ParentProduct");

                    b.Navigation("ProductSubType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductTypeEntity", "ProductType")
                        .WithMany("ProductSubTypes")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterial")
                        .WithMany()
                        .HasForeignKey("GroupMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMaterial");

                    b.Navigation("ProductSubTypeWorkingPeriodSample");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStageSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubType")
                        .WithMany("ProductSubTypeStageSamples")
                        .HasForeignKey("ProductSubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubType")
                        .WithMany("ProductSubTypeWorkingPeriodSamples")
                        .HasForeignKey("ProductSubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "Product")
                        .WithMany("Stages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "Product")
                        .WithMany("WorkingPeriods")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ChildProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ChildProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ParentProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ParentProductSubTypeWorkingPeriodSampleEntityId");

                    b.Navigation("ChildProductSubTypeWorkingPeriodSampleEntity");

                    b.Navigation("ParentProductSubTypeWorkingPeriodSampleEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageBrigadeRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.BrigadeEntity", "BrigadeEntity")
                        .WithMany()
                        .HasForeignKey("BrigadeEntityId");

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", "WorkingPeriodStageEntity")
                        .WithMany()
                        .HasForeignKey("WorkingPeriodStageEntityId");

                    b.Navigation("BrigadeEntity");

                    b.Navigation("WorkingPeriodStageEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSample")
                        .WithMany("WorkingPeriodStages")
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodEntity", "WorkingPeriod")
                        .WithMany("WorkingPeriodStages")
                        .HasForeignKey("WorkingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWorkingPeriodSample");

                    b.Navigation("WorkingPeriod");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterial")
                        .WithMany("WorkingPeriodStageMaterials")
                        .HasForeignKey("GroupMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", "WorkingPeriodStage")
                        .WithMany("WorkingPeriodStageMaterials")
                        .HasForeignKey("WorkingPeriodStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMaterial");

                    b.Navigation("WorkingPeriodStage");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageTypeRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", "ProductSubTypeWorkingPeriodSampleEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWorkingPeriodSampleEntity");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("ProductSubTypeWorkingPeriodSampleEntityProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", null)
                        .WithMany()
                        .HasForeignKey("ChildProductSubTypeWorkingPeriodSamplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", null)
                        .WithMany()
                        .HasForeignKey("ParentProductSubTypeWorkingPeriodSamplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductSubTypeWorkingPeriodSampleEntityProductSubTypeWorki~1");
                });

            modelBuilder.Entity("ProductSubTypeWorkingPeriodSampleEntityStageTypeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", null)
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodSamplesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("StageTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Navigation("Brigades");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Navigation("WorkingPeriodStageMaterials");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Navigation("ChildProducts");

                    b.Navigation("Stages");

                    b.Navigation("WorkingPeriods");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.Navigation("ProductSubTypeStageSamples");

                    b.Navigation("ProductSubTypeWorkingPeriodSamples");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodSampleEntity", b =>
                {
                    b.Navigation("WorkingPeriodStages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductSubTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageTypeEntity", b =>
                {
                    b.Navigation("Brigades");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.Navigation("WorkingPeriodStages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Navigation("WorkingPeriodStageMaterials");
                });
#pragma warning restore 612, 618
        }
    }
}
