// <auto-generated />
using System;
using KssGroupPlanning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KssGroupPlanning.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250916062623_new_entities_v4")]
    partial class new_entities_v4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CountEmployee")
                        .HasColumnType("integer");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FactoryId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("Brigades");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GroupMaterials");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.MaterialSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("End_date")
                        .HasColumnType("date");

                    b.Property<Guid?>("FactoryEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Start_date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactoryEntityId");

                    b.HasIndex("OrderEntityId");

                    b.HasIndex("ParentProductEntityId");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeEntityId");

                    b.ToTable("ProductSubTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeWorkingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialId");

                    b.HasIndex("ProductSubTypeWorkingPeriodsSampleId");

                    b.ToTable("ProductSubTypeGroupMaterialRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStagesSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("ProductSubTypeStagesSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StandartEmployee")
                        .HasColumnType("integer");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingPeriodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("ProductSubTypeWorkingPeriodsSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.SrcOrderEntity", b =>
                {
                    b.Property<string>("OrderName")
                        .HasColumnType("text");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Dogovor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LogisticDate")
                        .HasColumnType("date");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SchemeDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderName");

                    b.ToTable("SrcOrders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StageTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntityId");

                    b.ToTable("WorkingPeriods");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrigadeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Recycling")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrigadeId");

                    b.HasIndex("ProductSubTypeWorkingPeriodsSampleId");

                    b.HasIndex("WorkingPeriodId");

                    b.ToTable("WorkingPeriodStages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateDelivery")
                        .HasColumnType("date");

                    b.Property<Guid>("GroupMaterialEntitiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupMaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkingPeriodStageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupMaterialEntitiesId");

                    b.HasIndex("WorkingPeriodStageEntityId");

                    b.ToTable("WorkingPeriodStageMaterials");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodsRelationsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChildProductSubTypeWokingPeriodsSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildProductSubTypeWokingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentProductSubTypeWokingPeriodsSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentProductSubTypeWokingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildProductSubTypeWokingPeriodsSampleEntityId");

                    b.HasIndex("ParentProductSubTypeWokingPeriodsSampleEntityId");

                    b.ToTable("WorkingPeriodsRelations");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodsStageTypesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeWokingPeriodsSampleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeWokingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWokingPeriodsSampleEntityId");

                    b.HasIndex("StageTypeId");

                    b.ToTable("WorkingPeriodStageTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.BrigadeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "Factory")
                        .WithMany()
                        .HasForeignKey("FactoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factory");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "FactoryEntity")
                        .WithMany("Products")
                        .HasForeignKey("FactoryEntityId");

                    b.HasOne("KssGroupPlanning.Entities.OrderEntity", "OrderEntity")
                        .WithMany("Products")
                        .HasForeignKey("OrderEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ParentProductEntity")
                        .WithMany("ChildProductEntities")
                        .HasForeignKey("ParentProductEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("FactoryEntity");

                    b.Navigation("OrderEntity");

                    b.Navigation("ParentProductEntity");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductTypeEntity", "ProductTypeEntity")
                        .WithMany("ProductSubTypeEntities")
                        .HasForeignKey("ProductTypeEntityId");

                    b.Navigation("ProductTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeGroupMaterialRelationEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterial")
                        .WithMany()
                        .HasForeignKey("GroupMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ProductSubTypeWorkingPeriodsSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodsSampleId");

                    b.Navigation("GroupMaterial");

                    b.Navigation("ProductSubTypeWorkingPeriodsSample");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStagesSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ProductEntity")
                        .WithMany()
                        .HasForeignKey("ProductEntityId");

                    b.Navigation("ProductEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.BrigadeEntity", "Brigade")
                        .WithMany()
                        .HasForeignKey("BrigadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ProductSubTypeWorkingPeriodsSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodsSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodEntity", "WorkingPeriod")
                        .WithMany()
                        .HasForeignKey("WorkingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brigade");

                    b.Navigation("ProductSubTypeWorkingPeriodsSample");

                    b.Navigation("WorkingPeriod");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageMaterialEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.GroupMaterialEntity", "GroupMaterialEntities")
                        .WithMany("workingPeriodStageMaterialEntities")
                        .HasForeignKey("GroupMaterialEntitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodStageEntity", "WorkingPeriodStageEntity")
                        .WithMany("workingPeriodStageMaterialEntities")
                        .HasForeignKey("WorkingPeriodStageEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMaterialEntities");

                    b.Navigation("WorkingPeriodStageEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodsRelationsEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ChildProductSubTypeWokingPeriodsSampleEntity")
                        .WithMany()
                        .HasForeignKey("ChildProductSubTypeWokingPeriodsSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ParentProductSubTypeWokingPeriodsSampleEntity")
                        .WithMany()
                        .HasForeignKey("ParentProductSubTypeWokingPeriodsSampleEntityId")
                        .HasConstraintName("FK_WorkingPeriodsRelations_ProductSubTypeWorkingPeriodsSample~1");

                    b.Navigation("ChildProductSubTypeWokingPeriodsSampleEntity");

                    b.Navigation("ParentProductSubTypeWokingPeriodsSampleEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodsStageTypesEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ProductSubTypeWokingPeriodsSampleEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWokingPeriodsSampleEntityId");

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWokingPeriodsSampleEntity");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.GroupMaterialEntity", b =>
                {
                    b.Navigation("workingPeriodStageMaterialEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Navigation("ChildProductEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductSubTypeEntities");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Navigation("workingPeriodStageMaterialEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
