// <auto-generated />
using System;
using KssGroupPlanning;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KssGroupPlanning.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Factories");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.MaterialSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MaterialSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("End_date")
                        .HasColumnType("date");

                    b.Property<Guid?>("FactoryEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FactoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Start_date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FactoryEntityId");

                    b.HasIndex("OrderEntityId");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeEntityId");

                    b.ToTable("ProductSubTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStagesSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.ToTable("ProductSubTypeStagesSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductSubTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductSubTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StageTypeEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StageTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("StandartEmployee")
                        .HasColumnType("integer");

                    b.Property<string>("StandartTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkingPeriodName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeEntityId");

                    b.HasIndex("StageTypeEntityId");

                    b.ToTable("ProductSubTypeWorkingPeriodsSamples");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.SrcOrderEntity", b =>
                {
                    b.Property<string>("OrderName")
                        .HasColumnType("text");

                    b.Property<string>("Contragent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Dogovor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("LogisticDate")
                        .HasColumnType("date");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentCurrent")
                        .HasColumnType("numeric");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("SchemeDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderName");

                    b.ToTable("SrcOrders");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Stages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StageTypes");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductEntityId");

                    b.ToTable("WorkingPeriods");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductSubTypeWorkingPeriodsSampleId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("Recycling")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductSubTypeWorkingPeriodsSampleId");

                    b.HasIndex("WorkingPeriodId");

                    b.ToTable("WorkingPeriodStages");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.FactoryEntity", "FactoryEntity")
                        .WithMany("Products")
                        .HasForeignKey("FactoryEntityId");

                    b.HasOne("KssGroupPlanning.Entities.OrderEntity", "OrderEntity")
                        .WithMany("Products")
                        .HasForeignKey("OrderEntityId");

                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("FactoryEntity");

                    b.Navigation("OrderEntity");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductTypeEntity", "ProductTypeEntity")
                        .WithMany("ProductSubTypeEntities")
                        .HasForeignKey("ProductTypeEntityId");

                    b.Navigation("ProductTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeStagesSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeEntity", "ProductSubTypeEntity")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeEntityId");

                    b.HasOne("KssGroupPlanning.Entities.StageTypeEntity", "StageTypeEntity")
                        .WithMany()
                        .HasForeignKey("StageTypeEntityId");

                    b.Navigation("ProductSubTypeEntity");

                    b.Navigation("StageTypeEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.StageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductEntity", "ProductEntity")
                        .WithMany()
                        .HasForeignKey("ProductEntityId");

                    b.Navigation("ProductEntity");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.WorkingPeriodStageEntity", b =>
                {
                    b.HasOne("KssGroupPlanning.Entities.ProductSubTypeWorkingPeriodsSampleEntity", "ProductSubTypeWorkingPeriodsSample")
                        .WithMany()
                        .HasForeignKey("ProductSubTypeWorkingPeriodsSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KssGroupPlanning.Entities.WorkingPeriodEntity", "WorkingPeriod")
                        .WithMany()
                        .HasForeignKey("WorkingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductSubTypeWorkingPeriodsSample");

                    b.Navigation("WorkingPeriod");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.FactoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.OrderEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KssGroupPlanning.Entities.ProductTypeEntity", b =>
                {
                    b.Navigation("ProductSubTypeEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
